src/myapp/urls.py
from django.urls import path
from myapp.views import *

urlpatterns = [
    path('', upload, name='upload'),
    path('show_doc/', show_doc, name='show_doc'),
    path('choices/', choices, name='choices'),
    path('download/', download, name='download'),
    path('sample/', sample, name='sample'),
    path('upload_cdrive/', upload_cdrive, name='upload_cdrive'),
    path('exit_app/', exit_app, name='exit_app'),
    path('clean/', clean_strings, name='clean_strings'),
]

src/mysite/urls.py
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
] + static('/static/', document_root=settings.STATIC_ROOT)

src/myapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Document(models.Model):
    docfile = models.FileField(upload_to='documents')

src/myapp/forms.py
from django import forms

PROFILER_CHOICES = (('1', 'Find Similarity'), ('2', 'Profile'), ('3', 'Find Errors'))

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label = 'Select a File',
        help_text = 'max. 42 megabytes',
        required = False
    )

class ProfilerChoiceForm(forms.Form):
    profiler_choice_label = forms.ChoiceField(widget=forms.RadioSelect, choices=PROFILER_CHOICES)

src/myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt
import pandas as pd
import os, sys, json
import requests
import pdb
from myapp.models import Document
from myapp.forms import DocumentForm
from utils.utils import *

REDIRECT_URI = os.environ["CDRIVE_URL"] + "app/" + os.environ["COLUMBUS_USERNAME"] + "/string-prepper/"
APP_ID = os.environ["COLUMBUS_CLIENT_ID"]
APP_SECRET = os.environ["COLUMBUS_CLIENT_SECRET"]
TOKEN_URL = os.environ["AUTHENTICATION_URL"] + "o/token/"
AUTH_URL = os.environ["AUTHENTICATION_URL"] + "o/authorize/" + "?response_type=code" + "&client_id=" + os.environ["COLUMBUS_CLIENT_ID"] + "&redirect_uri=" + REDIRECT_URI + "&state=1234xyz"
CDRIVE_URL = os.environ["CDRIVE_API_URL"]
CDRIVE_UI_URL = os.environ["CDRIVE_URL"]
CLIENT_TOKEN_KEY = "procleaner_token"
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
CDRIVE_FILES_DIR = os.path.join(PROJECT_DIR, "cdrive_files")
CLEAN_FILES = os.path.join(os.path.join(os.path.join(os.path.join(PROJECT_DIR, "myapp"), "static"), "pdf"), "clean")
CLEAN_FILES_LOCAL = os.path.join(os.path.join(os.path.join(os.path.join(PROJECT_DIR, "myapp"), "static"), "pdf"), "clean_local")
CLEAN_FILES_CDRIVE = os.path.join(os.path.join(os.path.join(os.path.join(PROJECT_DIR, "myapp"), "static"), "pdf"), "clean_cdrive")
CLEAN_FILES_SUFFIX = ".clean"

def upload(request):
    """
    View for rendering upload page of the application.
    This view performs the following operations:
        1. Create a form consisting of an input field for a user to upload a file.
        2. Get the OAuth token for the user from authentication (if it doesn't
           exist).
        3. Get the list of files in current users' CDrive.
        4. Render the form and CDrive files.
    Arguments:
        request: The request object.
    Returns an HttpResponse object.
    """
    form = DocumentForm()
    if CLIENT_TOKEN_KEY not in request.session:
        if 'code' in request.GET:
            code = request.GET.get('code')
            data = {
                "grant_type": "authorization_code",
                "code": code,
                "redirect_uri": REDIRECT_URI,
                "client_id": APP_ID,
                "client_secret": APP_SECRET,
            }
            response = requests.post(
                url=TOKEN_URL,
                data=data
            )
            request.session[CLIENT_TOKEN_KEY] = response.json()['access_token']
            request.session.set_expiry(response.json()['expires_in'])
        else:
            return HttpResponseRedirect(AUTH_URL)
    return render(
        request,
        'upload.html',
        {'form': form, 'c_drive_ui_url': CDRIVE_UI_URL}
    )

def sample(request):
    """
    View for rendering the sample tuples of the uploaded file.
    This view does the following:
        1. Read the upload type.
        2. Save the uploaded file locally.
        3. Set session parameters to reference the file subsequently.
        4. Read and return a sample of tuples.
    Arguments:
        request: The request object.
    Returns an HttpResponse object.
    """
    upload_type = ""
    cdrive_file_path = request.POST.get('cdriveFile')
    if cdrive_file_path is not None:
        upload_type = "CDrive"
    elif 'docfile' in request.FILES:
        upload_type = "Local"
    if upload_type == "CDrive":
        token = request.session[CLIENT_TOKEN_KEY]
        get_url = CDRIVE_URL + "content/?path=" + str(cdrive_file_path)
        header = {"Authorization": "Bearer " + token}
        read_response = requests.get(url=get_url, headers=header)
        tuples = read_response.json().split("\n")
        uploaded_df = pd.DataFrame(tuples)
        uploaded_df.columns = ['foo']
        uploaded_df['id'] = range(0, len(uploaded_df))
        column_order = ['id', 'foo']
        if not os.path.exists(CDRIVE_FILES_DIR):
            os.makedirs(CDRIVE_FILES_DIR)
        index = cdrive_file_path.rfind("/")
        cdrive_file = cdrive_file_path[index+1:]
        parent_path = cdrive_file_path[0:index]
        uploaded_df[column_order].to_csv(os.path.join(CDRIVE_FILES_DIR, cdrive_file), index=False)
        sample_tuples = tuples[1:10]
        request.session['uploaded_file'] = cdrive_file
        request.session['cdrive_path'] = parent_path
        request.session['file_type'] = "CDrive"
    elif upload_type == "Local":
        uploaded_doc = Document(docfile=request.FILES['docfile'])
        uploaded_doc.save()
        uploaded_doc_path = os.path.join(PROJECT_DIR, uploaded_doc.docfile.url[1:])
        uploaded_df = pd.read_csv(uploaded_doc_path, names=['foo'])
        uploaded_df['id'] = range(0, len(uploaded_df))
        column_order = ['id', 'foo']
        whitespace_striper = lambda x: str(x).strip()
        uploaded_df['foo'] = uploaded_df['foo'].apply(whitespace_striper)
        uploaded_df[column_order].to_csv(uploaded_doc_path, index=False)
        request.session['uploaded_file'] = uploaded_doc.docfile.url
        request.session['uploaded_file_name'] = uploaded_doc.docfile.name
        request.session['file_type'] = "Local"
        sample_tuples = uploaded_df['foo'].head(10).tolist()
    return render(request, 'sample.html', {'sample_tuples': sample_tuples})

def choices(request):
    """
    View for rendering the choices for profiling and cleaning.
    Arguments:
        request: The request object.
    Returns an HttpResponse object.
    """
    profiler_options = [["1", "Clean Strings"], ["2", "Profile Strings"], ["3", "Debug Strings"]]
    return render(request, 'choices.html', {'profiler_options': profiler_options})

@csrf_exempt
def upload_cdrive(request):
    """
    View for uploading the clean file to CDrive.
    This view does the following:
        1. Retrives the path of clean file on local.
        2. Uploads the file to CDrive using it's API.
    Arguments:
        request: The request object.
    Returns an HttpResponse object.
    """
    uploaded_file = request.session.get('uploaded_file')
    parent_path = request.session.get('cdrive_path')
    clean_file_name = os.path.basename(uploaded_file) + CLEAN_FILES_SUFFIX
    clean_file_path = os.path.join(CLEAN_FILES, clean_file_name)
    files = {'file': (clean_file_name, open(clean_file_path, 'rb')), 'path': (None, parent_path)}
    post_url = CDRIVE_URL + "upload/"
    token = request.session[CLIENT_TOKEN_KEY]
    header = {"Authorization": "Bearer " + token}
    try:
        upload_response = requests.post(post_url, files=files, headers=header)
        django_response = HttpResponse(
            content=upload_response.content,
            status=upload_response.status_code,
            content_type=upload_response.headers['Content-Type']
        )
    except:
        django_response = HttpResponseBadRequest
    return django_response

@csrf_exempt
def exit_app(request):
    """
    View for performing a clean exit when the user wants to go back to CDrive.
    This view does the following:
        1. Delete any session data stored (Token, etc).
        2. Delete uploaded and cleaned files, if they exist. 
        3. Delete model object, if it exists.
    Arguments:
        request: The request object.
    Returns an empty HttpResponse object.
    """
    if "uploaded_file" in request.session:
        uploaded_file = request.session.get('uploaded_file')
        del request.session["uploaded_file"]   
    if "file_type" in request.session:
        if request.session["file_type"] == "CDrive":
            uploaded_file_path = os.path.join(CDRIVE_FILES_DIR, uploaded_file)
        else:
            uploaded_file_path = os.path.join(PROJECT_DIR, uploaded_file[1:])
            uploaded_file_name = request.session.get('uploaded_file_name')
            Document.objects.filter(docfile=uploaded_file_name).delete()
        if os.path.exists(uploaded_file_path):
            os.remove(uploaded_file_path)
        clean_file_name = os.path.basename(uploaded_file) + CLEAN_FILES_SUFFIX
        clean_file_path = os.path.join(CLEAN_FILES, clean_file_name)
        if os.path.exists(clean_file_path):
            os.remove(clean_file_path)
    if CLIENT_TOKEN_KEY in request.session:
        del request.session[CLIENT_TOKEN_KEY]
    if "file_type" in request.session:
        del request.session["file_type"]
    if "uploaded_file_name" in request.session:
        del request.session["uploaded_file_name"]
    if "cdrive_path" in request.session:
        del request.session["cdrive_path"]
    return HttpResponse('')

def download(request):
    """
    View for rendering the download page of the application.
    Arguments:
        request: The request object.
    Returns an HttpResponse object.
    """
    uploaded_file = request.session.get('uploaded_file')
    if request.session["file_type"] == "CDrive":
        uploaded_file_path = os.path.join(CDRIVE_FILES_DIR, uploaded_file)
    else:
        uploaded_file_path = os.path.join(PROJECT_DIR, uploaded_file[1:])
    clean_file_name = os.path.basename(uploaded_file) + CLEAN_FILES_SUFFIX
    clean_file_path = os.path.join(CLEAN_FILES, clean_file_name)
    if not os.path.exists(CLEAN_FILES):
        os.makedirs(CLEAN_FILES)
    uploaded_df = pd.read_csv(uploaded_file_path)
    uploaded_df.to_csv(clean_file_path, index=False)
    return render(request,
                  'download.html',
                      {
                          'clean_file_name': clean_file_name,
                          'clean_file_path': clean_file_path,
                          'c_drive_ui_url': CDRIVE_UI_URL
                      }
                 )

def clean_strings(request):
    """
    View for performing value normalization part of the application.
    This view does the following:
        1. Retrives the file name from the session.

src/myapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/procleaner.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  
  <body style="background-color: azure;">
    {% block content %}
    {%  endblock %}
    <script>
      {% block script %}
      {% endblock %}
    </script>
  </body>
</html>

src/myapp/templates/choices.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-md-12">
        <h1>
          String Profiling and Cleaning Options
        </h1>
        <p class="lead">Please select one of the following options</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form id="formChoices" onsubmit="return validateForm()" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            {% for option in profiler_options %}
              <b>
              <label class="control control--radio">{{ option.1 }}
                <input type="radio" name="profiler_choice" value="{{ option.0 }}">
                <div class="control__indicator"></div>
              </label>
              </b>
            {% endfor %}
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <button id="btnSubmit" type="submit" value="Submit" class="btn btn-primary">Execute</button>
            <button type="button" value="backUpload" id="backtouploadbtn" class="btn btn-default">Back to Upload Page</button>
          </div>
        </div>
        <div class="row">
          <div id="errorBox" class="col-md-4 col-md-offset-4" style="display: none;">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
function validateForm() {
  var choice = $("input[name='profiler_choice']:checked").val();
  if(choice === undefined) {
    errorBoxHtml = '\
                <br> \
                <div class="alert alert-dismissible alert-danger"> \
                    <button type="button" class="close" data-dismiss="alert">&times;</button> \
                    <strong>Error: Please select a choice</strong> \
                  </div>';
    $("#errorBox").html(errorBoxHtml);
    $("#errorBox").show();
    return false;
  } else {
    var choice_num = parseInt(choice, 10) - 1;
    var views = ["{% url 'clean_strings' %}", "{% url 'show_doc' %}", "{% url 'show_doc' %}"];
    $("#formChoices").attr('action', views[choice_num]);
    console.log(views[choice_num]);
    return true;
  }
} 
$(document).ready(function(){
  $("#backtouploadbtn").click(function(){
    document.location.href = "{% url 'upload' %}";
  });
});
{% endblock %}

src/myapp/templates/clean_strings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-md-12">
        <h1>
          Clean Strings
        </h1>
        <p class="lead">
          <ol>
            <li><b>Select strings</b> that you want to merge.</li>
            <li>Click on a <b>Merge</b> button (Normalize selected strings - the selected strings will be replaced by
              the longest one)</li>
            <li> <b>Merge</b> as many as you can on the screen</li>
            <li> When you are done with the strings on screen, click <b>Clean Up</b> </li>
              <li>Clicking <b>Clean Up</b> will push the merges to file level, and show you a new set of strings to merge.</li>
            <li> <b>Repeat</b> the merge and clean up until you are done with cleaning up the file for now.</li>
            <li> Make sure to press Clean up before you press I'm done</li>
            <li> Press <b>I'm done </b>(you can always proceed with further cleaning on the new cleaned file, that
              you'll
              download on next screen)</li>
          </ol>
        </p>
      </div>
    </div>
  </div>
  {% if show_normalizer %}
    <div class="row">
      <div class="col-md-12">
        <div class="well bs-component">
          <form action="{% url 'clean_strings' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-4">
                <div class="item col-sm-12">
                  <center>
                    <button type="button" value="Merge" class="mergebtn btn btn-primary">Merge</button>
                    <input id="mergeval" type="hidden" name="merge" value="" />
                    <br><br>
                  </center>
                  <table class="table table-striped table-hover ">
                    <tbody>
                      {% for s in similar_strings_1 %}
                        <tr class="info">
                          <td>
                            <label class="control control--checkbox">
                              <input style="display:inline;" type="checkbox" name="clean" value="{{ s }}" />{{ s }}
                              <div class="control__indicator"></div>
                            </label>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="item col-sm-12">
                  <center>
                    <button type="button" value="Merge" class="mergebtn btn btn-primary">Merge</button>
                    <input id="mergeval" type="hidden" name="merge" value="" />
                    <br><br>
                  </center>
                  <table class="table table-striped table-hover ">
                    <tbody>
                      {% for s in similar_strings_2 %}
                        <tr class="info">
                          <td>
                            <label class="control control--checkbox">
                              <input style="display:inline;" type="checkbox" name="clean" value="{{ s }}" />{{ s }}
                              <div class="control__indicator"></div>
                            </label>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <center>
                    <button type="button" value="Merge" class="mergebtn btn btn-primary">Merge</button>
                    <input id="mergeval" type="hidden" name="merge" value="" />
                  </center>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="item col-sm-12">
                  <center>
                    <button type="button" value="Merge" class="mergebtn btn btn-primary">Merge</button>
                    <input id="mergeval" type="hidden" name="merge" value="" />
                    <br><br>
                  </center>
                  <table class="table table-striped table-hover ">
                    <tbody>
                      {% for s in similar_strings_3 %}
                        <tr class="info">
                          <td>
                            <label class="control control--checkbox">
                              <input style="display:inline;" type="checkbox" name="clean" value="{{ s }}" />{{ s }}
                              <div class="control__indicator"></div>
                            </label>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 text-center">
                <br>
                <button type="submit" value="Clean Up" class="btn btn-info">Clean Up (Show next set of entries to
                  merge)</button>
                <input id="mergeval" type="hidden" name="merge" value="" />
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 text-center">
                <br>
                <button type="button" value="Done" id="donebtn" class="btn btn-success">I'm Done</button>
                <input id="mergeval" type="hidden" name="merge" value="" />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  {% else %}
    <div class="row">
      <div class="item col-md-12">
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Couldn't find any strings to clean</strong>
        </div>
      </div>
    </div>
  {% endif %}
  <div class="row">
    <div class="col-md-12">
      <button type="button" value="backChoice" id="backtoprofilerchoicebtn" class="btn btn-default">Back to
        Choices</button>
      <button type="button" value="backUpload" id="backtouploadbtn" class="btn btn-default">Back to Upload Page</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <br>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
$(document).ready(function() {
  $(".mergebtn").click(function(){
    var current_merge = []
    var retain_val = ""
    $.each($("input[name='clean']:checked"), function() {
      current_string = $(this).val();
      if (retain_val.length < current_string.length) { 
        retain_val=current_string; 
      } 
      current_merge.push($(this).val()); 
    });
    $.each($("input[name='clean' ]:checked"), function() { 
      current_val=$(this).val(); $(this).val("");
      parent=$(this).parent(); $(this).parent().css("background-color", "#8FBC8F" ); 
      parent_html=$(this).parent().html();
      new_parent_html=parent_html.split(">")[0] + ">" + retain_val;
      console.log("New parent");
      console.log(new_parent_html);
      $(this).parent().html(new_parent_html);
      console.log(parent);
      console.log($(parent).children());
      $(this).val(retain_val);
      $(this).prop("checked", false);
    });
    current_merge_val = $("#mergeval").val();
    append_val = retain_val + "," + current_merge.join(",");
    if (current_merge_val == "") {
      current_merge_val = append_val;
    } else {
      current_merge_val = current_merge_val + "|" + append_val;
    }
    $("#mergeval").val(current_merge_val);
    console.log(retain_val);
    console.log(current_merge.join(","));
    console.log(current_merge_val);
  });
  $("#donebtn").click(function(){
    document.location.href = "{% url 'download' %}";
  });
  $("#backtoprofilerchoicebtn").click(function(){
    document.location.href = "{% url 'choices' %}";
  });
  $("#backtouploadbtn").click(function(){
    document.location.href = "{% url 'upload' %}";
  });
});
{% endblock %}

src/myapp/templates/sample.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-md-12">
        <h1>
          Confirm File
        </h1>
        <p class="lead">Look at the sample from the file and confirm if this is the intended upload.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-hover ">
        <tbody>
          {% for t in sample_tuples %}
            <tr class="info">
              <td>{{ t }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button type="button" value="Confirm" id="confirmbtn" class="btn btn-primary">Confirm</button>
      <button type="button" value="backUpload" id="backtouploadbtn" class="btn btn-default">Back to Upload Page</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <br>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
$(document).ready(function() {
  $("#confirmbtn").click(function(){
    document.location.href = "{% url 'choices' %}";
  });
  $("#backtouploadbtn").click(function(){
    document.location.href = "{% url 'upload' %}";
  });
});
{% endblock %}

src/myapp/templates/upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
  <div class="page-header" id="banner">
    <div class="row">
      <div class="col-md-12">
        <h1>
          Upload a file
        </h1>
        <p class="lead">Choose from amongst the two options</p>
      </div>
    </div>
  </div>
  <div class="row">
      
    <div class="col-md-3 col-md-offset-3 text-center">
      <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#uploadLocal">
        Upload from Local
      </button>
    </div>
    <div class="col-md-3 text-center">
      <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#uploadCDrive">
        Upload from C Drive
      </button>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-md-12">
      <div id="uploadLocal" class="collapse">
        <div class="well bs-component">
          <form action="{% url 'sample' %}" onsubmit="return validateFormLocal()" method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <fieldset>
              <legend>Upload from Local </legend>
              <div class="form-group">
                <div class="col-lg-12">
                    <p>{{ form.non_field_errors }}</p>
                    <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
                    <p>
                      {{ form.docfile.errors }}
                      {{ form.docfile }}
                    </p>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-12">
                  <button type="submit" value="Upload" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
      <div id="uploadCDrive" class="collapse">
        <div class="well bs-component">
          <form action="{% url 'sample' %}" onsubmit="return validateFormCDrive()" method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <fieldset>
              <legend>Select a file from CDrive</legend>
              <div class="form-group">
                <div class="col-lg-12">
		  <input id="cdrive-file-input" type="text" name="cdriveFile"/>
                </div>
              </div>
              <div class="form-group">
                <div class="col-lg-12">
                  <button type="submit" value="Upload" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div id="errorBox" class="col-md-12" style="display:none;">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <button type="button" value="backCDrive" id="backtoCbtn" class="btn btn-default">Back to C Drive</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <br>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
function validateFormCDrive() {
  var localFile = $("#id_docfile")[0].files[0];
  var cdriveFile = $("#cdrive-file-input").val();
  var isValid = true;
  if(localFile != undefined) {
    isValid = false;
    if(cdriveFile === '') {
      errorMessage = "Error: Please select a file from CDrive or click on the Submit button for uploading local file.";
    } else {
      errorMessage = "Error: Please select only one option to upload the file (Local or CDrive).";
    }
  } else {
    if(cdriveFile === '') {
      isValid = false;  
      errorMessage = "Error: Please select a file from CDrive.";
    }
  }
  if(!isValid) {
    errorBoxHtml = "<br> \
          <div class=\"alert alert-dismissible alert-danger\"> \
            <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button> \
            <strong id=\"errorMessage\"></strong> \
          </div>";
    $("#errorBox").html(errorBoxHtml);
    $("#errorMessage").html(errorMessage);
    $("#errorBox").show();
  }
  return isValid;
}
function validateFormLocal() {
  var localFile = $("#id_docfile")[0].files[0];
  var cdriveFile = $("#cdrive-file-input").val();
  var isValid = true;
  if(cdriveFile != '') {
    isValid = false;
    if(localFile === undefined) {
      errorMessage = "Error: Please select a file locally or click on the Submit button for uploading file from CDrive.";
    } else {
      errorMessage = "Error: Please select only one option to upload the file (Local or CDrive).";
    }
  } else {
    if(localFile === undefined) {
      isValid = false;  
      errorMessage = "Error: Please select a file from Local.";
    } else if(localFile.size === 0) {
      isValid = false;  
      errorMessage = "Error: The uploaded file is empty.";
    }
  }
  if(!isValid) {
    errorBoxHtml = "<br> \
          <div class=\"alert alert-dismissible alert-danger\"> \
            <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button> \
            <strong id=\"errorMessage\"></strong> \
          </div>";
    $("#errorBox").html(errorBoxHtml);
    $("#errorMessage").html(errorMessage);
    $("#errorBox").show();
  }
  return isValid;
}
$(document).ready(function() {
  $("#backtoCbtn").click(function(){
    $.ajax({
      type: "POST",
      url: 'myapp/exit_app/',
      success: function(data) {
        document.location.href = "{{ c_drive_ui_url }}";
      }
    });
  });
});
{% endblock %}